package test;

import java.awt.*;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;


public class ImageWindow extends javax.swing.JFrame {
    private final BufferedImage image;

    public ImageWindow(BufferedImage image) {
        initComponents();
        this.image = image;
        setTitle("MgVulkanTest");
        jPanelGraphics.setPreferredSize(new Dimension(640, 480));
        pack();
        setLocationRelativeTo(null);
        repaint();
    }

    private void draw(Graphics g){
        g.drawImage(image, 0, 0, rootPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanelGraphics = new JPanel(){
            @Override
            public void paint(Graphics g) {
                draw(g);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout jPanelGraphicsLayout = new javax.swing.GroupLayout(jPanelGraphics);
        jPanelGraphics.setLayout(jPanelGraphicsLayout);
        jPanelGraphicsLayout.setHorizontalGroup(
                jPanelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelGraphicsLayout.setVerticalGroup(
                jPanelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelGraphics);

        pack();
    }// </editor-fold>
//    public static void main(String args[]) {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                int w = 128;
////                int h = 128;
////                BufferedImage image = new BufferedImage(w, h, BufferedImage.TYPE_4BYTE_ABGR);
////                for(int x = 0; x < w; x++){
////                    for(int y = 0; y < h; y++){
////                        int r = x * 2;
////                        int g = 0;
////                        int b = y * 2;
////                        int a = 255;
////                        image.setRGB(x, y, new Color(r, g, b, a).getRGB());
////                    }
////                }
////                new ImageWindow(image).setVisible(true);
////            }
////        });
//    }
    // Variables declaration - do not modify
    private javax.swing.JPanel jPanelGraphics;
    // End of variables declaration
}
